
pipeline_name: OCR

text_type: general

use_doc_preprocessor: True
use_textline_orientation: True

SubPipelines:
  DocPreprocessor:
    pipeline_name: doc_preprocessor
    use_doc_orientation_classify: True
    use_doc_unwarping: True
    SubModules:
      DocOrientationClassify:
        module_name: doc_text_orientation
        model_name: PP-LCNet_x1_0_doc_ori
        model_dir: /app/model/ocr/LCNet_x1_0_doc_ori_infer
      DocUnwarping:
        module_name: image_unwarping
        model_name: UVDoc
        model_dir: /app/model/ocr/UVDoc_infer

SubModules:
  TextDetection:
    module_name: text_detection
    model_name: PP-OCRv5_mobile_det
    model_dir: /app/model/ocr/PP-OCRv5_mobile_det_infer
    limit_side_len: 64
    limit_type: min
    max_side_limit: 4000
    thresh: 0.3
    box_thresh: 0.6
    unclip_ratio: 1.5
  TextLineOrientation:
    module_name: textline_orientation
    model_name: PP-LCNet_x1_0_textline_ori 
    model_dir: /app/model/ocr/PP-LCNet_x1_0_textline_ori_infer
    batch_size: 6    
  TextRecognition:
    module_name: text_recognition
    model_name: PP-OCRv5_server_rec
    model_dir: /app/model/ocr/PP-OCRv5_server_rec_infer
    batch_size: 6
    score_thresh: 0.0
